# Numpy Basics
- Numpy.arrays are homogeneous multidimensional array.
- array.array can only handle only one dimential array. 

In [1]:
# Import numpy
import numpy as np

# Creation of 4*4 array

a = np.arange(16).reshape(4, 4) # arange(x) [0,1,2,3,4......x]

# Attributes of ndarray

shape = a.shape # it gives the dimensions of the matrix (n, m) 
dimensions = a.ndim # Number of dimensions
size = a.size # Total number of elements 
Data_type = a.dtype.name # type of the elements ex: int32 float64
Object_type = type(a) 

print(shape)
print(dimensions)
print(size)
print(Data_type)
print(Object_type)

(4, 4)
2
16
int32
<class 'numpy.ndarray'>


## Array Creation

In [12]:
c = np.array([1,2,3,4,5]) 
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)], dtype = 'float64' )
a_dtype = a.dtype.name
b_dtype = b.dtype.name
print(a_dtype)
print(b_dtype)

int32
float64


 ## array of zeros or ones

In [18]:
# array of zeros or ones
a = np.zeros((4,4), dtype = np.float64)
b = np.ones((4,4))
print(a)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


## Generation of random numbers from different distributions.

In [3]:
a = np.random.rand() # rand generates a uniform distribution over [0,1)
b = np.random.rand(2,2)
c = np.random.randn() # randn generates standred normal distribution. 
d = np.random.normal(0, 10, 20) # Random number from a normal distribution with mean = 0, standard deviation = 10 
e = np.random.randint(0,16,16)  #16 random int btw 0 & 16

## Generate sequence of numbers

In [25]:
a = np.arange(0,10,0.5) # Start = 0, End = 10, Intervel = 0.5

# If you do not know the length of the intervel

b = np.linspace(0,10,20) # Start = 0, End = 10, #digits = 20


array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

## np.zeros_like, np.ones_like, empty_like

In [30]:
a = np.arange(9).reshape((3,3))
b = np.zeros_like(a)
c = np.ones_like(a)
d = np.empty_like(a)

print(a)
print(b)
print(c)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[-466179688        577 2080595712]
 [1678010880 1913219845 2080924740]
 [1678073600  687887111 1393981961]]


## ****fromfunction, fromfile

## Arithmetic operators on arrays apply elementwise

In [34]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a*b                  # Elementwise product
d = a+b 
e = a.dot(b)             # Matrix multiplication 
f = np.dot(a, b)         # Matrix multiplication 
g = a**2                 # a raised to the power of 2
h = a<3                  
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]
[ 6  8 10 12]
70
70
[ 1  4  9 16]
[ True  True False False]


## Sum, min and max.

In [27]:
a = np.array([(1,2,3,4,5,6),(7,8,9,10,11,12)])
minimum = a.min()
maximum = a.argmax()
sum_a = a.sum()

print(minimum)
print(maximum)
print(sum_a)



1
5
78


## Location of min & max

In [28]:
a = np.arange(10).reshape(2,5)
loc_min_1_row = a[0,:].argmin()
loc_max_2_row = a[1,:].argmax()
print(loc_min_1_row)
print(loc_max_2_row)

0
4


## Applying an operation along the specified axis of an array.

In [41]:
a = np.arange(20).reshape(4,5)
 
# axis = 0 (column), axis = 1 (row)

Column_sum = a.sum(axis = 0)      # sum of each element in a column
row_product = a.prod(axis = 1)    # product of each element in a row
print(a)
print(Column_sum)
print(row_product)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[      0   15120  240240 1395360]


## Numpy.apply_along_axis

In [44]:
def Squ_and_sum(a):
    result = 0
    for i in range(len(a)):
        result += a[i]**2
    return(result)
a = np.arange(20).reshape(4,5)
b = np.apply_along_axis(Squ_and_sum, 1, a)
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  30  255  730 1455]


## Argmax, argmin and argsort

In [50]:
a= np.random.randn(9).reshape(3,3)
b = np.argmax(a,axis = 0) # index of max value in each column
print(a)
print(b)

[[-0.23164917 -1.21513463 -1.13636278]
 [ 2.29833036  1.26171602 -1.00785839]
 [-0.86895048  1.71938815 -0.14711293]]
[1 2 2]


## numpy.vectorize

## Numpy.Where

In [61]:
a = np.arange(0,20,0.5)
b = np.where(a > 4)       # result is the index
c = a[np.where(a > 4)]
print(b)
print(c)

(array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], dtype=int64),)
[  4.5   5.    5.5   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.
  10.5  11.   11.5  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.
  16.5  17.   17.5  18.   18.5  19.   19.5]


## Numpy.isin

In [2]:
a = np.arange(10)
b = np.arange(7,20,1)
c = np.isin(a, b)
d = np.where(c)
print(c)
print(d)

[False False False False False False False  True  True  True]
(array([7, 8, 9], dtype=int64),)


##   ***fromfunction

In [23]:
# Construct an array by executing a function over each coordinate.
def f(x, y):
    if (x>y):
        return 1
    else:
        return 0
#np.fromfunction(f,(3,3),dtype=int)
# def f(x,y):
#     return 10*x+y
# b = np.fromfunction(f,(5,4),dtype=int)
# b

c = f(4,3)
c
        

1

## Indexing and Slicing 

In [65]:
a = np.arange(20)
a1 = np.arange(20).reshape(4,5)
b = a[2]        # select the element with index 2
c = a[10:15]    # from [10 to 15)
d = a[:10:2]    # from [0 to 10) select every 2nd number
e = a[ : :-1]   # revers array a
f = a[-1]       # - is used to access from back of an array
g = a1[-1, :]   # last row, all column
h = a[:-7]      # removal of last 7 numbers
h

# a[1, : , : ] can also be written as a[1,..]



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Iteration

In [70]:
a = np.arange(20).reshape(4,5)

# iteration through each row
for i in a:
    print(i)

# iteration through all te elements
for j in a.flat:
    print(j)
# Iteration through each column
for k in range(a.shape[1]):
    print(a[:,k])

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


False

## Combining arrays

In [59]:
a = np.arange(0,10,1).reshape((2,5))
b = np.arange(10,20,1).reshape((2,5))

# adding rows of a & b (vertical stacking)
c = np.vstack([a,b])
print(c)

# adding columns of a & b (horizontal stacking)
d = np.hstack([a,b])
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


## Splitting of an array

In [48]:
a = np.arange(20).reshape(2,10)

# split a into 2 horizontly
b,c = np.hsplit(a,2)

# Spliting by specing the column number
d,e,f = np.hsplit(a,(4,6))

# split a into 2 vertically
g,h = np.vsplit(a,2)


## Copie & View

In [ ]:
a = np.array([1,2,3])

b = a  # No new object is created a & b are two names of a same array

# Different array objects can share the same data. The view method creates a new array object that looks at the same data.
c = a.view()

# The copy method makes a complete copy of the array and its data.
d = a.copy()



## Indexing

In [6]:
a = np.arange(10)**2  # array of the squars of digits 0 to 9 
b = np.array([3,5,7]) 
c = a[b]
d = np.array([(1,3,5,7),(2,4,6,8)])
e = a[d]
e

array([[ 1,  9, 25, 49],
       [ 4, 16, 36, 64]], dtype=int32)

In [64]:
a = np.arange(9).reshape(3,3)
b = a[0,2]
b
c = a[0][2]    # a[x,y] = a[x][y]
c

2

In [55]:
a = np.arange(5)
a[[0,2,4]] = 0    # updating the values in an array

a[[1,1,2]] += 1   # add 1 to the specified locations and they are updated only once

a

array([0, 2, 1, 3, 0])

## Boolean Array

In [57]:
a = np.arange(16).reshape(4,4)
b = a < 9       # find the locations of a greater than 9
print(b)
c = a[b]
c

[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]
 [False False False False]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Broadcasting

A      (4d array):  8 x 1 x 6 x 1, 
B      (3d array):      7 x 1 x 5, 
Result (4d array):  8 x 7 x 6 x 5.


In [66]:
a = np.arange(10)
b = 2             # in numpy smaller array are broadcasted to the larger array to match the size 
c = a * b
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Structured arrays

In [78]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],              
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
a = x[1]
print(a)
b = x['weight']
print(b)

('Fido', 3,  27.)
[ 81.  27.]


## Find indices of non-zero elements

In [79]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


## Padding

In [81]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


## numpy.nan

In [82]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan
False


## finding common values between two arrays

In [51]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
c = np.intersect1d(a,b)
print(c)
print(a,b)

# How to remove from one array those items that exist in another?
d = np.isin(a,c)
print(d)
e = np.where(d == True,False,True)
print(e)
f = a[e]
print(f)




[0 1 3 7 8]
[5 4 5 4 3 7 4 0 1 8] [7 7 3 0 7 6 7 8 1 6]
[False False False False  True  True False  True  True  True]
[ True  True  True  True False False  True False False False]
[5 4 5 4 4]


## Sorting

In [96]:
a = np.random.randint(0,10,10)
a.sort()
a

array([0, 1, 1, 2, 3, 4, 4, 5, 6, 7])

## Checking if two arrays are equal or not

In [97]:
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
c = np.array_equal(a,b)
c

False

## Subtract the mean of each row of a matrix

In [102]:
a = np.random.randint(0,16,16).reshape(4,4)
b = a.mean(axis = 1,keepdims = True)
c = a - b
print(a)
print(b)
print(c)


[[ 1  5  6 13]
 [ 5  5  6  1]
 [11  9  0  1]
 [ 9  1 13  4]]
[[ 6.25]
 [ 4.25]
 [ 5.25]
 [ 6.75]]
[[-5.25 -1.25 -0.25  6.75]
 [ 0.75  0.75  1.75 -3.25]
 [ 5.75  3.75 -5.25 -4.25]
 [ 2.25 -5.75  6.25 -2.75]]


## sort an array by one of it's columns.

In [29]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])  # Sorting through its 3rd column

[[6 8 3]
 [0 0 7]
 [2 3 6]]
[[6 8 3]
 [2 3 6]
 [0 0 7]]


## Finding out odd numbers

In [40]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.where(a % 2 != 0)
c = a[b]
c

array([1, 3, 5, 7, 9])

## How to replace items that satisfy a condition with another value in numpy array?

In [44]:
a = np.arange(30)
for i in range(len(a)):
    if a[i] % 2 == 0:
        a[i] = 0

# Using np
b = np.arange(30)
b[b % 2 == 0] = 0
b

# or
c = np.arange(30)
d = np.where(c % 2 == 0, 0, c)
d


array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29])

## How to print only n decimal places in python numpy array?

In [53]:
a = np.random.random([5,3])
np.set_printoptions(precision=3)
a


array([[ 0.86 ,  0.182,  0.231],
       [ 0.38 ,  0.537,  0.688],
       [ 0.471,  0.442,  0.843],
       [ 0.305,  0.627,  0.017],
       [ 0.49 ,  0.805,  0.954]])

## Finding the nth percentile value

In [64]:
a = np.random.random(100)
a.sort()
percentile = 10
length = len(a)
index =((np.rint((length*percentile)/100))-1)
print(a)
a[int(index)]

[ 0.019  0.024  0.038  0.062  0.073  0.087  0.09   0.094  0.094  0.101
  0.106  0.112  0.117  0.128  0.141  0.155  0.16   0.164  0.164  0.181
  0.186  0.244  0.247  0.247  0.248  0.249  0.249  0.262  0.267  0.268
  0.27   0.275  0.277  0.285  0.291  0.309  0.318  0.32   0.329  0.339
  0.34   0.354  0.372  0.396  0.396  0.416  0.417  0.427  0.467  0.479
  0.491  0.492  0.542  0.543  0.555  0.584  0.587  0.619  0.631  0.635
  0.657  0.668  0.697  0.699  0.713  0.716  0.722  0.729  0.736  0.754
  0.756  0.778  0.782  0.784  0.786  0.787  0.793  0.795  0.808  0.819
  0.819  0.822  0.832  0.86   0.869  0.872  0.873  0.876  0.883  0.884
  0.888  0.905  0.907  0.91   0.913  0.959  0.986  0.989  0.994  0.999]


0.10113521914360357

a = np.arange(16).reshape(4,4)
print(a)
b = a[:,3]
b.reshape(4,1)
c= np.append(a,b,0)
c

## What is the value of second longest petallength of species setosa

In [17]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

setosa = iris[iris[:,4] == b'Iris-setosa']
setosa[setosa[:,2].argsort()][-2]


array([b'5.1', b'3.8', b'1.9', b'0.4', b'Iris-setosa'], dtype=object)

## Find the most frequent value of petal length in iris dataset

In [45]:
uq,ct=np.unique(iris[:,2], return_counts = True)
uq[ct.argsort()[-1]]

b'1.5'

## How to convert a numeric to a categorical (text) array
Less than 3 --> 'small'
3-5 --> 'medium'
'>=5 --> 'large'                                                  
Bin the petal length 

In [118]:
iris1 = iris.copy()
iris1[:,2]=iris1[:, 2].astype('float')
for i in range(iris.shape[0]):
    if iris1[i,2] < 3.0:
        iris1[i,2] = 'Small'
    elif (iris1[i,2] >= 3.0)&(iris1[i,2] < 5.0):
        iris1[i,2] = 'medium'
    elif iris1[i,2] >= 5:
        iris1[i,2] = 'Large'
        
# method 2

a = np.digitize(iris[:,2].astype('float'),[0,3,5,10])
labels = {1: 'small', 2: 'medium', 3: 'large'}
for j in range(iris.shape[0]):
    iris[j,2] = labels.get(a[j])  

## Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [139]:
a =( np.pi * iris[:,2].astype('float') * iris[:,0].astype('float')**2 ) / 3
a = a.reshape(150,1)
b = np.append(iris,a.reshape(150,1),1)
b.shape

(150, 6)

## How to find the position of the first occurrence of a value greater than a given value?

In [22]:
iris2 = iris
iris2[:,3]=iris2[:,3].astype('float')
a = np.array(np.where(iris2[:,3] > 1))
iris2[a[:,0],3]

# method 2
iris2[np.argwhere(iris2[:,3] > 1)[0], 3 ]     

array([1.4], dtype=object)

## From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [30]:
a = np.random.randint(1,100,50)
b = np.where(a < 10, 10, np.where(a > 30, 30, a) )
b

# method 2
np.clip(a, a_min = 10, a_max = 30)


array([30, 30, 10, 12, 30, 22, 30, 10, 30, 30, 23, 30, 30, 30, 30, 30, 30,
       30, 30, 10, 29, 14, 30, 30, 30, 30, 15, 30, 16, 22, 28, 29, 30, 30,
       30, 23, 30, 30, 28, 30, 30, 30, 30, 30, 30, 15, 23, 30, 30, 30])

## Get the positions of top 5 unique maximum values in a given array a

In [73]:
np.random.seed(100)
a = np.random.randint(1,50,20)
b =np.unique(a).reshape(1,15)
np.where(np.isin(a,b[0,-5:]))
print(a)

[ 9 25  4 40 24 16 49 11 31 35  3 35 15 35 49 25 16 37 44 17]


## **Compute the counts of unique values row-wise.

In [133]:
np.random.seed(100)
a = np.random.randint(1,11,size = (6, 10))
counter = np.zeros(a.shape, dtype = 'int')
b = [np.unique(row, return_counts = True) for row in a]
x = ([c[d == i] if i in a else 0 for i in np.unique(a)] for c , d in b) 

x


<generator object <genexpr> at 0x0000026A07C12518>

## one-hot encodings for an array in numpy

In [121]:
a = np.random.randint(1,5,10)
b = np.unique(a)
c = np.zeros((len(a),len(b)))
for i, j in enumerate(a):
    c[i,j-1] = 1

print(a,b,c)

[3 2 1 4 1 4 3 4 4 3] [1 2 3 4] [[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]]


## Create row numbers grouped by a categorical variable.

In [152]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
a = np.sort(np.random.choice(species, size=20))
b =np.array([0])
x = 0
for i in range(len(a)-1):
    if a[i] == a[i+1]:
        x += 1
        b = np.append(b,x)
    else:
        x = 0
        b = np.append(b,x)
print(a,b) 
    

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'] [0 1 2 3 4 5 0 1 2 3 4 5 6 7 0 1 2 3 4 5]


## Compute the min-by-max for each row for given 2d numpy array.

In [2]:
a = np.arange(20).reshape(4,5)

np.apply_along_axis(lambda x: np.min(x)/np.max(x), 1, a )

array([ 0.        ,  0.55555556,  0.71428571,  0.78947368])

## How to find the duplicate records in a numpy array

In [16]:
a = np.random.randint(1,20,20)
b,c = np.unique(a, return_index = True)
d = np.full(a.shape[0],True)
d[c] = False
print(a,d)

[ 3  1 19  6 11  8 11  6 12  7  2  7 14  7  4  3  7 18  5 13] [False False False False False False  True  True False False False  True
 False  True False  True  True False False False]


## Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

In [33]:
c = np.array([])
for i in np.unique(iris[:,4]):
    b = np.mean(iris[np.where(iris[:,4] == i),0].astype('float'))
    c = np.append(c,[i,b],axis = 0)

array([b'Iris-setosa', b'5.006', b'Iris-versicolor', b'5.936',
       b'Iris-virginica', b'6.588'],
      dtype='|S32')

## How to drop all missing values from a numpy array
Input : np.array([1,2,3,np.nan,5,6,7,np.nan])                              output : array([ 1.,  2.,  3.,  5.,  6.,  7.])

In [37]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([ 1.,  2.,  3.,  5.,  6.,  7.])

## Compute the euclidean distance between two arrays a and b.

In [45]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
c = np.sqrt(((a-b)**2).sum())
c

6.7082039324993694

## Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [65]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
c = np.array([])
for i in range(1,len(a)-1):
    if (a[i]-a[i-1] > 0) and (a[i]-a[i+1] > 0):
        c = np.append(c,[i],axis=0)

#method2:
d = np.diff(np.sign(np.diff(a)))
np.where(d == -2)[0] + 1

array([2, 5], dtype=int64)

## Find the index of 5th repetition of number 1 in x

In [73]:
a = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(a == 1)[0][4]

8

## Compute the moving average of window size 3, for the given 1D array

In [95]:
np.random.seed(100)
n = 3
a = np.random.randint(10, size=10)
c = np.array([])
for i in range(len(a)-n-1):
    c=np.append(c,[a[i:(i+n)].mean().round(2)], axis = 0)
c

(6,)

##     ******From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

In [86]:
a = np.arange(20)
wl = 4
s = 2
c = np.array([],shape=(0,wl))
for i in range(np.floor((len(a)-wl)/s).astype('int')):
    c = np.append(c,[a[i*s:(i*s+wl)]], axis = 0)
c

TypeError: 'shape' is an invalid keyword argument for this function

## How to import and export data as a csv file

In [161]:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype='float')

array([  1.80000000e+01,   8.00000000e+00,   3.07000000e+02,
         1.30000000e+02,   3.50400000e+03,   1.20000000e+01,
         7.00000000e+01,   1.00000000e+00,  -9.99000000e+02])

## How to save and load numpy objects

In [170]:
a = np.arange(10)
b = np.arange(30)
np.save('a.npy',a)    # saving a in a.npy
np.savez('a_b.npz', a, b)
c = np.load('a.npy')
d = np.load('a_b.npz')
d