# Supervised learning
Supervised learning is mainly divided into classification and regression
<br>
supervised learning will have two types of variables
<br>
X - Independent Variables       Y - Dependent Variables (Target)
<br>
We use fit(X, Y) to train a model and use predict(X) to predict Y for an unknown X.

In [4]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [8]:
print(X.shape)
print(Y.shape)
print('Unique values of Y' + str(np.unique(Y)))

(150, 4)
(150,)
Unique values of Y[0 1 2]


## k-Nearest neighbors classifier

### Splitting of data into test and train

In [11]:
np.random.seed(100)
index = np.random.permutation(len(X))
X_train = X[index[:-20]]
Y_train = Y[index[:-20]]
X_test = X[index[-20:]]
Y_test = Y[index[-20:]]

In [12]:
# fitting of data 
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [24]:
# Predicting using the trained model
a = KNN.predict(X_test)
print(a, Y_test)

[2 1 1 1 1 2 2 0 0 1 1 1 1 2 1 1 2 1 0 0] [2 1 1 1 1 2 2 0 0 1 1 1 1 2 1 1 2 1 0 0]


## Linear Regression

In [31]:
diabetes = datasets.load_diabetes()
diabetes_X_train = diabetes.data[:-20]
diabetes_X_test  = diabetes.data[-20:]
diabetes_y_train = diabetes.target[:-20]
diabetes_y_test  = diabetes.target[-20:]

In [32]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(diabetes_X_train, diabetes_y_train)
print(regr.coef_)

[  3.03499549e-01  -2.37639315e+02   5.10530605e+02   3.27736980e+02
  -8.14131709e+02   4.92814588e+02   1.02848452e+02   1.84606489e+02
   7.43519617e+02   7.60951722e+01]


In [35]:
# Mean square error
np.mean((regr.predict(diabetes_X_test)-diabetes_y_test)**2)

2004.5676026898225

In [37]:
# R^2 Value
reg.score(diabetes_X_test, diabetes_y_test) 

0.58507530226905713

## Ridge Regression

In [38]:
## loss function = (y_pred - y)^2 + alpha(weights)^2
RR = linear_model.Ridge(alpha=.1)
RR.fit(diabetes_X_train, diabetes_y_train)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [46]:
RR.coef_

array([  11.1136556 , -204.19946801,  480.69629861,  303.83348865,
        -88.06728559,  -66.87260956, -193.14729968,  119.53475526,
        430.10894133,   95.56293006])

In [40]:
RR.score(diabetes_X_test, diabetes_y_test)

0.57058999437280111

In [42]:
np.logspace(-4, -1, 6)

array([ 0.0001    ,  0.00039811,  0.00158489,  0.00630957,  0.02511886,
        0.1       ])

In [45]:
alphas = np.logspace(-4, -1, 6)
print([RR.set_params(alpha=alpha
            ).fit(diabetes_X_train, diabetes_y_train,
            ).score(diabetes_X_test, diabetes_y_test) for alpha in alphas]) 

[0.58511106838835336, 0.58520730154446765, 0.5854677540698493, 0.58555120365039159, 0.58307170855541623, 0.57058999437280111]


## Lasso (least absolute shrinkage and selection operator)

In [57]:
laso = linear_model.Lasso()
alphas = np.logspace(-4, -1, 6)

# scors for different values of alphas
scores = [laso.set_params(alpha = x).fit(diabetes_X_train, diabetes_y_train)
         .score(diabetes_X_test, diabetes_y_test) for x in alphas]
# Select the model with highest score
best_alpha = alphas[np.where(scores == max(scores))]
laso.alpha = best_alpha
laso.fit(diabetes_X_train, diabetes_y_train)
laso.coef_

array([   0.        , -212.43764548,  517.19478111,  313.77959962,
       -160.8303982 ,   -0.        , -187.19554705,   69.38229038,
        508.66011217,   71.84239008])

## logistic Regression 

In [59]:
logistic = linear_model.LogisticRegression()
logistic.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

## SVM

In [60]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(X_train, Y_train)   

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## Exercise to try

In [61]:
from sklearn import datasets, neighbors, linear_model

digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target

In [69]:
print(X_digits.shape)
print(y_digits.shape)
np.unique(y_digits)

(1797, 64)
(1797,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
test_, train_  = 0.1, 0.9 # split percentage
np.random.seed(100)
index = np.random.permutation(len(X_digits))
x_train = X_digits[index[:-(np.round_(len(X_digits)*test_).astype(int))]]
y_train = y_digits[index[:-(np.round_(len(X_digits)*test_).astype(int))]]
x_test  = X_digits[index[-(np.round_(len(X_digits)*test_).astype(int)):]]
y_test  = y_digits[index[-(np.round_(len(X_digits)*test_).astype(int)):]]

In [99]:
# Knn
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
print('score for Knn is '+ str(knn.score(x_test, y_test)))

# Logistic
logistic = linear_model.LogisticRegression()
logistic.fit(x_train, y_train)
print('score for logistic is '+ str(logistic.score(x_test, y_test)))

# SVM
svc1 = svm.SVC(kernel = 'linear')
svc1.fit(x_train, y_train)
print('score for svc linear is '+ str(svc1.score(x_test, y_test)))

svc2 = svm.SVC(kernel = 'poly', degree = 3)
svc2.fit(x_train, y_train)
print('score for svc poly is '+ str(svc2.score(x_test, y_test)))

svc3 = svm.SVC(kernel = 'rbf')
svc3.fit(x_train, y_train)
print('score for svc Radial Basis Function is '+ str(svc3.score(x_test, y_test)))


score for Knn is 0.983333333333
score for logistic is 0.933333333333
score for svc linear is 0.972222222222
score for svc poly is 0.988888888889
score for svc Radial Basis Function is 0.488888888889
