## Import 

In [2]:
import numpy as np  
import pandas as pd

## How to create a series from a list, numpy array and dict

In [8]:
a = np.arange(10)
b = np.arange(10,20,1)
c = dict(zip(a,b))
df = pd.Series(c)
df

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

## Convert the series ser into a dataframe with its index as another column on the dataframe.

In [12]:
frame = df.to_frame().reset_index()
frame

index   0
0      0  10
1      1  11
2      2  12
3      3  13
4      4  14
5      5  15
6      6  16
7      7  17
8      8  18
9      9  19

## Combine ser1 and ser2 to form a dataframe

In [8]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.DataFrame({'one':ser1,'two':ser2} )


## Give a name to the series ser calling it ‘alphabets’.

In [13]:
a = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
b = pd.Series(np.arange(26))
b.index = a 
b

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32

## From a remove items present in b.

In [15]:
a = pd.Series(np.arange(5))
b = pd.Series(np.arange(3,10,1))
a[~np.isin(a,b)]

0    0
1    1
2    2
dtype: int32

## Get all items of ser1 and ser2 not common to both.

In [18]:
a = pd.Series(np.arange(5))
b = pd.Series(np.arange(3,10,1))
x = a[~np.isin(a,b)].append(b[~np.isin(b,a)])
x

0    0
1    1
2    2
2    5
3    6
4    7
5    8
6    9
dtype: int32

## Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

In [20]:
ser = pd.Series(np.random.normal(10, 5, 25))
ser.describe()

# Method 2
np.percentile(ser, q = [0,25,50,75,100])

array([  2.86542184,   9.80284903,  11.06092536,  13.55087708,  17.5830807 ])

## Calculte the frequency counts of each unique value ser

In [24]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts().index    # for unique values
ser.value_counts()          # for unique value count

a    7
d    6
e    4
g    4
b    3
h    3
c    2
f    1
dtype: int64

## From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.


In [40]:

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
a = ser.value_counts().index[:2]
ser[~np.isin(ser,a)] = 'others'
ser

0     others
1     others
2          d
3     others
4     others
5          d
6     others
7          d
8     others
9          d
10    others
11    others
12         g
13         g
14    others
15         g
16         d
17         d
18    others
19         g
20    others
21    others
22         g
23         d
24    others
25    others
26    others
27         d
28         d
29    others
dtype: object

## Bin the series ser into 10 equal deciles and replace the values with the bin name.

In [4]:
ser = pd.Series(np.random.random(20))
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1],
       labels=[1,2,3,4,5,6,7,8,9,10])

0      1
1      3
2      7
3      4
4      1
5      6
6      9
7      8
8      2
9      7
10     8
11     5
12     3
13     2
14     5
15    10
16     6
17     9
18    10
19     4
dtype: category
Categories (10, int64): [1 < 2 < 3 < 4 ... 7 < 8 < 9 < 10]

## Reshape the series into a dataframe with 7 rows and 5 columns

In [7]:
a = pd.Series(np.arange(35))
b = pd.DataFrame(a.values.reshape(7,5))
b

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34

## Find the positions of numbers that are multiples of 3 from ser.

In [9]:
a = pd.Series(np.arange(30))
a[a % 3 == 0]

0      0
3      3
6      6
9      9
12    12
15    15
18    18
21    21
24    24
27    27
dtype: int32

## From a, extract the items at positions in list pos.

In [10]:
a = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
a[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

## Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

In [12]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Vertically
ser3 = ser1.append(ser2,ignore_index= True)

# Horizontally
s = {1:ser1,2:ser2}
ser4 = pd.DataFrame(s)
ser4

1  2
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

## Get the positions of items of ser2 in ser1 as a list.

In [58]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

## Compute the mean squared error of truth and pred series.

In [67]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
a = truth - pred
np.mean(a**2)

0.19599373470487996

## Change the first character of each word to upper case in each word of ser.

In [90]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: x[0].upper()+x[1:])

0     how
1      to
2    kick
3    ass?
dtype: object

## How to calculate the number of characters in each word in a series?

In [91]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x:len(x))

0    3
1    2
2    4
3    4
dtype: int64

## Difference of differences between the consequtive numbers of ser.

In [98]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
np.diff(np.diff(ser))


array([1, 1, 1, 1, 0, 2], dtype=int64)

## How to convert a series of date-strings to a timeseries?

In [104]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# methode1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

#methode2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## Get the day of month, week number, day of year and day of week from ser.

In [114]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
a = ser.map(lambda x: parse(x))

# day of the month
a.dt.day.tolist()

# Week number
a.dt.weekofyear.tolist()

#day of year
a.dt.dayofyear.tolist()

# day of week
a.dt.weekday_name.tolist()

['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

## Change ser to dates that start with 4th of the respective months.

In [135]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

a = ser.map(lambda x: parse(x))
b = a.map(lambda y: str(y.year)+'-'+'04'+'-'+str(y.month))
#Method1
c = b.map(lambda z: parse(z))
#method2
pd.to_datetime(b)

0   2010-04-01
1   2011-04-02
2   2012-04-03
dtype: datetime64[ns]

## How to filter words that contain atleast 2 vowels from a series?

In [205]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
v = np.array(['a','e','i','o','u'])
#method1
x = np.array([])
for i in range(len(ser)):
    a = np.unique(list(ser[i].lower()))
    if len(a[np.isin(a, v)]) > 1:
        x = np.append(x,ser[i])
x

array(['Apple', 'Orange', 'Money'],
      dtype='<U32')

## Compute the mean of weights of each fruit.

In [209]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
dfd = {'fruit1':fruit,'weight':weights}
df = pd.DataFrame(dfd)
df.groupby('fruit1').mean()

weight
fruit1        
apple      5.6
banana     4.0
carrot     7.5

## Compute the euclidean distance between series (points) p and q, without using a packaged formula.

In [214]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
(((p-q)**2).sum()**0.5)

18.16590212458495

## Get the peaks (values surrounded by smaller values on both sides) in ser.

In [230]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
a = np.diff(np.sign(np.diff(ser)))
ser[np.where(a == -2)[0]+1]

1    10
5    10
7     7
dtype: int64

## Replace the spaces in my_str with the least frequent character.

In [278]:
my_str = 'dbc deb abed gade'
x = np.unique(list(my_str), return_counts = True)
ans = ''
for i in my_str:
    if i == ' ':
        ans = ans + str(x[0][np.where(x[1] == x[1].min())][0])
    else:
        ans = ans + str(i)
ans

'dbccdebcabedcgade'

## How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [286]:
a = {1:pd.date_range('2000-01-01', periods = 10, freq='W-SAT'), 2:np.random.randint(1,10,10)}
b = pd.Series(a)
b


1    DatetimeIndex(['2000-01-01', '2000-01-08', '20...
2                       [9, 8, 6, 3, 6, 7, 4, 7, 8, 8]
dtype: object

## ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.

In [305]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser1 = pd.Series(index = pd.date_range(ser.index.min(),ser.index.max()))
for x in ser1.index:
    if x in ser.index:
        ser1[x] = ser[x]
        a = ser[x]
    else:
        ser1[x] = a
ser1

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

## Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

ans = [ser.autocorr(x) for x in range(len(ser))]
ans

## Import every 50th row of BostonHousing dataset as a dataframe.

In [313]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
df2

age       b  chas      crim     dis  indus  lstat  medv    nox  \
0     65.2  396.90   0.0   0.00632  4.0900   2.31   4.98  24.0  0.538   
50    45.7  395.56   0.0   0.08873  6.8147   5.64  13.45  19.7  0.439   
100   79.9  394.76   0.0   0.14866  2.7778   8.56   9.42  27.5  0.520   
150   97.3  372.80   0.0   1.65660  1.6180  19.58  14.10  21.5  0.871   
200   13.9  384.30   0.0   0.01778  7.6534   1.47   4.45  32.9  0.403   
250   13.0  396.28   0.0   0.14030  7.3967   5.86   5.90  24.4  0.431   
300   47.4  390.86   0.0   0.04417  7.8278   2.24   6.07  24.8  0.400   
350   44.4  396.90   0.0   0.06211  8.7921   1.25   5.98  22.9  0.429   
400  100.0  396.90   0.0  25.04610  1.5888  18.10  26.77   5.6  0.693   
450   92.6    0.32   0.0   6.71772  2.3236  18.10  17.44  13.4  0.713   
500   79.7  396.90   0.0   0.22438  2.4982   9.69  14.33  16.8  0.585   

     ptratio   rad     rm    tax    zn  
0       15.3   1.0  6.575  296.0  18.0  
50      16.8   4.0  5.963  243.0  21.0  
100     20.9   5.0  6.727  384.0   0.0  
150     14.7   5.0  6.122  403.0   0.0  
200     17.0   3.0  7.135  402.0  95.0  
250     19.1   7.0  6.487  330.0  22.0  
300     14.8   5.0  6.871  358.0  70.0  
350     19.7   1.0  6.490  335.0  40.0  
400     20.2  24.0  5.987  666.0   0.0  
450     20.2  24.0  6.749  666.0   0.0  
500     19.2   6.0  6.027  391.0   0.0

## Import the boston housing dataset, but while importing change the 'medv' (median house value) column so that values < 25 becomes ‘Low’ and > 25 becomes ‘High’.

In [316]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low' })

## Import ‘crim’ and ‘medv’ columns of the BostonHousing dataset as a dataframe

In [321]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])

## Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

In [331]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
np.where(df.values == np.max(df.Price))

(array([58], dtype=int64), array([4], dtype=int64))